=== eduvallejo33/HTML-2-Trimestre/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="biblioteca.xsl"?>
<!-- W3C Schema generated by XMLSpy v2022 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="biblioteca">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="libro" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="miki.webp"/>
				<xs:enumeration value="senda.webp"/>
				<xs:enumeration value="summer.webp"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="libro">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="foto"/>
				<xs:element ref="titulo"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="titulo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Miki"/>
				<xs:enumeration value="Senda"/>
				<xs:enumeration value="Summer"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== eduvallejo33/HTML-2-Trimestre/biblioteca.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="biblioteca.xsl"?>
<?xml-stylesheet href="biblioteca.css"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblioteca.xsd">
	<libro>
		<foto>miki.webp</foto>
		<titulo>Miki</titulo>
	</libro>
	<libro>
		<foto>senda.webp</foto>
		<titulo>Senda</titulo>
	</libro>
	<libro>
		<foto>summer.webp</foto>
		<titulo>Summer</titulo>
	</libro>
</biblioteca>
